In [1]:
import os

# 准备工作
必须: 为了使用`cuda`，请依次点击`runtime`-`Change runtime type`, 选择`Hardware Acceleration`为`GPU`

# 需要修改的参数
若有些需要在特定位置修改，会在这里说明

In [15]:
# 视频
# 如果是自定义视频，将其上传到根目录下，并命名为input.mp4 (注意格式转换)
youtube_video_url = "https://www.youtube.com/watch?v=UpH7rm0cYbM" # 如果不用yutube视频，放置空字符串
cut_video_start_time = "00:00:42"
cut_video_time_interval = "00:00:05"

# 依赖
# 在 安装依赖 这节里，安装 Detectron2 需要根据 torch 和 cuda 版本安装，请到提示位置手动复制官网安装流程里 Install Pre-Built Detectron2 (Linux only) 的安装代码
# 官网 https://detectron2.readthedocs.io/en/latest/tutorials/install.html

# 下载数据
download_joint_coordinates = True
download_video = False

# 获取和处理视频

## 下载 yt-dlp 用于下载youtube视频

In [3]:
if youtube_video_url == "":
    raise Exception("若不用youtube视频,请将下面的代码注释。")
!rm yt-dlp # 避免重复下载导致很多个yt-dlp,强迫症 ○|￣|_ =3
!wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
!chmod a+rx ./yt-dlp
!./yt-dlp -f mp4 --output "input.%(ext)s"  $youtube_video_url

rm: cannot remove 'yt-dlp': No such file or directory
--2022-01-28 13:55:45--  https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/yt-dlp/yt-dlp/releases/download/2022.01.21/yt-dlp [following]
--2022-01-28 13:55:46--  https://github.com/yt-dlp/yt-dlp/releases/download/2022.01.21/yt-dlp
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/307260205/dd225b1a-65a4-428b-8977-887a12ba94f7?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220128%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220128T135546Z&X-Amz-Expires=300&X-Amz-Signature=a7b5c7e97da99b9df6372807537c15bed4d58a50fd76cb74231d266d436616b0&X-Amz-SignedHeaders=host&acto

## 处理视频

In [4]:
!rm -rf ./videos
!mkdir videos
!ffmpeg -y -loglevel info -i input.mp4 -ss $cut_video_start_time -t $cut_video_time_interval videos/video.mp4

ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lib

# 安装依赖

In [5]:
print("torch 版本:")
!python -c 'import torch; print(torch.__version__)'
print()
print("cuda 版本:")
!nvcc --version

torch 版本:
1.10.0+cu111

cuda 版本:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0


In [6]:
# 请根据版本手动修改这里的代码(到官网复制)
!python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.10/index.html

Looking in links: https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.10/index.html
     |████████████████████████████████| 7.0 MB 331 kB/s 
     |████████████████████████████████| 130 kB 6.3 MB/s 
     |████████████████████████████████| 55 kB 2.9 MB/s 
     |████████████████████████████████| 145 kB 35.0 MB/s 
     |████████████████████████████████| 74 kB 3.4 MB/s 
     |████████████████████████████████| 843 kB 45.9 MB/s 
     |████████████████████████████████| 748 kB 42.0 MB/s 
     |████████████████████████████████| 596 kB 41.9 MB/s 
     |████████████████████████████████| 112 kB 51.2 MB/s 
  Created wheel for fvcore: filename=fvcore-0.1.5.post20220119-py3-none-any.whl size=65267 sha256=b6d2dcbbef32091edc545eac5801c71d985562c0f47a4d5e1aac5b4885d79d90
  Stored in directory: /root/.cache/pip/wheels/f3/b8/eb/61ed840f80d7198725bc061872b6019a7b3e9db4dbadf68083
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141230 sha256=e7b0

# 克隆VideoPose3D库

In [7]:
!rm VideoPose3D -rf
!git clone https://github.com/facebookresearch/VideoPose3D
!mkdir ./VideoPose3D/checkpoint

Cloning into 'VideoPose3D'...
remote: Enumerating objects: 121, done.
remote: Total 121 (delta 0), reused 0 (delta 0), pack-reused 121
Receiving objects: 100% (121/121), 9.53 MiB | 12.41 MiB/s, done.
Resolving deltas: 100% (41/41), done.


# 下载事先训练好的Pretrained Human3.6m Coco Model

In [8]:
os.chdir('VideoPose3D/checkpoint')
!wget https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_detectron_coco.bin
os.chdir('..')

--2022-01-28 13:56:31--  https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_detectron_coco.bin
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.22.75.142, 104.22.74.142, 172.67.9.4, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.22.75.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67892577 (65M) [application/octet-stream]
Saving to: ‘pretrained_h36m_detectron_coco.bin’

pretrained_h36m_det 100%[===================>]  64.75M  19.9MB/s    in 3.7s    

2022-01-28 13:56:35 (17.3 MB/s) - ‘pretrained_h36m_detectron_coco.bin’ saved [67892577/67892577]



# 用Detectron2计算2D坐标

In [9]:
# !mkdir ../output
# os.chdir('inference')
# !python infer_video_d2.py \
#     --cfg COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x.yaml \
#     --output-dir ../../ouput \
#     --image-ext mp4 \
#     ../../videos
# os.chdir('..')
!pwd
os.chdir('..')
!rm output -rf
!mkdir output
!python /content/VideoPose3D/inference/infer_video_d2.py \
    --cfg COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x.yaml \
    --output-dir output \
    --image-ext mp4 \
    videos

/content/VideoPose3D
model_final_997cc7.pkl: 313MB [00:14, 22.1MB/s]               
Processing videos/video.mp4
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --en

# 创建自定义数据集

In [11]:
!mkdir ./VideoPose3D/data/detectron2output
!cp output/video.mp4.npz VideoPose3D/data/detectron2output/video.mp4.npz
os.chdir('VideoPose3D/data') # 必须要到这个目录下执行
!python prepare_data_2d_custom.py -i detectron2output -o myvideos
os.chdir('../../')

Parsing 2D detections from detectron2output
Processing detectron2output/video.mp4.npz
120 total frames processed
0 frames were interpolated
----------
Saving...
Done.


# 计算三维坐标

In [12]:
!cp ./videos/video.mp4 VideoPose3D/video.mp4
os.chdir('VideoPose3D')
!python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject video.mp4 --viz-action custom --viz-camera 0 --viz-video video.mp4 --viz-output output.mp4 --viz-export outputfile --viz-size 6

Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='myvideos', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export='outputfile', viz_limit=-1, viz_no_ground_truth=False, viz_output='output.mp4', viz_size=6, viz_skip=0, viz_subject='video.mp4', viz_video='video.mp4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Tr

# 查看数据

## 3D 关节坐标

In [13]:
import numpy as np
data  = np.load('outputfile.npy')
lst = data
for item in lst:
    print(item)

[[-1.21899393e-06 -1.16881902e-05  3.60973900e-07]
 [-1.18659921e-01  4.96952096e-03 -4.08731541e-03]
 [-8.80016685e-02  4.21905398e-01  6.16836697e-02]
 [-6.31301105e-02  8.31771791e-01  2.15986878e-01]
 [ 1.18659914e-01 -4.97595407e-03  4.09030914e-03]
 [ 1.02894247e-01  4.15988684e-01  4.77530211e-02]
 [ 7.87695199e-02  8.23695183e-01  2.08460987e-01]
 [-6.56262320e-03 -2.21582502e-01 -3.15453261e-02]
 [ 1.74720436e-02 -4.68513072e-01 -6.64900541e-02]
 [ 5.95242530e-03 -5.13766289e-01 -1.63631648e-01]
 [ 1.06797479e-02 -6.20158911e-01 -1.23906240e-01]
 [ 1.33024216e-01 -3.95357370e-01 -3.60353030e-02]
 [ 2.13346303e-01 -1.65958717e-01  5.32076396e-02]
 [ 2.21233368e-01 -3.30512561e-02 -1.19110286e-01]
 [-1.07723549e-01 -4.07664835e-01 -4.90573756e-02]
 [-2.20572174e-01 -1.91394717e-01  2.92709321e-02]
 [-1.99163795e-01 -4.59902510e-02 -1.44575536e-01]]
[[-1.21820995e-06 -1.16398196e-05  5.41707550e-07]
 [-1.18376285e-01  4.56733163e-03 -3.28374421e-03]
 [-8.78730118e-02  4.21403229e

## 视频

In [14]:
def show_local_mp4_video(file_name, width=640, height=480):
  import io
  import base64
  from IPython.display import HTML
  video_encoded = base64.b64encode(io.open(file_name, 'rb').read())
  return HTML(data='''<video width="{0}" height="{1}" alt="test" controls>
                        <source src="data:video/mp4;base64,{2}" type="video/mp4" />
                      </video>'''.format(width, height, video_encoded.decode('ascii')))

show_local_mp4_video('output.mp4', width=960, height=720)

# 下载数据

In [16]:
from google.colab import files

if download_joint_coordinates:
    files.download('outputfile.npy')

if download_video:
    files.download('output.mp4')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>