In [23]:
import os

# 准备工作
必须: 为了使用`cuda`，请依次点击`runtime`-`Change runtime type`, 选择`Hardware Acceleration`为`GPU`

# 需要修改的参数
若有些需要在特定位置修改，会在这里说明

In [24]:
# 视频
# 如果是自定义视频，将其上传到根目录下，并命名为input.mp4 (注意格式转换)
# 注意下面的youtube_video_url 和 bilibili_video_url 其实也可以改为其他网站的视频url, 具体请分别参考:
# youtube_video_url可替换网站: https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md
# bilibili_video_url可替换网站: https://github.com/iawia002/lux#supported-sites

# youtube_video_url = "https://www.youtube.com/watch?v=UpH7rm0cYbM" # 如果不用yutube视频，直接 Ctrl + / 注释掉, 并在 处理和获取视频章节 注释掉相应的代码块
bilibili_video_url = "https://www.bilibili.com/video/BV1R5411u7jL?from=search&seid=6033013284712839027&spm_id_from=333.337.0.0" # 如果不用bilibili视频，直接Ctrl + / 注释掉，并在 处理和获取视频章节 注释掉相应的代码块
cut_video_start_time = "00:00:05" # 一般都需要裁剪的吧，不然动作不好分类，而且视频长了运行时间也慢
cut_video_time_interval = "00:00:05" # 如果要全部保留的话，修改第一个参数为"00:00:00"，第二个参数为总视频时长

# 依赖
# 在 安装依赖 这节里，安装 Detectron2 需要根据 torch 和 cuda 版本安装，请到提示位置手动复制官网安装流程里 Install Pre-Built Detectron2 (Linux only) 的安装代码
# 官网 https://detectron2.readthedocs.io/en/latest/tutorials/install.html

# 下载数据
download_joint_coordinates = True
download_video = True

In [25]:
varNames = list(vars().keys())
if "youtube_video_url" in varNames and "bilibili_video_url" in varNames:
    raise Exception("Youtube 和 Bilibili 中只能选一个")

# 获取和处理视频

## 下载 yt-dlp 用于下载youtube视频

In [26]:
# if "youtube_video_url" not in varNames:
#     raise Exception("若不用youtube视频,请将这里代码全部注释。")
# !rm yt-dlp # 避免重复下载导致很多个yt-dlp,强迫症 ○|￣|_ =3
# !wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
# !chmod a+rx ./yt-dlp
# !./yt-dlp -f mp4 --output "input.%(ext)s"  $youtube_video_url

## 下载 lux 用于下载 Bilibili视频

In [27]:
if "bilibili_video_url" not in varNames:
    raise Exception("若不用Bilibili视频,请将这里代码全部注释。")
!rm lux lux.tar.gz # 避免重复下载导致很多个强迫症 ○|￣|_ =3
!wget https://github.com/iawia002/lux/releases/download/v0.12.0/lux_0.12.0_Linux_64-bit.tar.gz -O lux.tar.gz # 作者偏偏要在每次发行的文件上加个版本号，这样搞得获取最新版要借助api，凑合吧
!tar -xvf ./lux.tar.gz
!chmod a+rx ./lux
!./lux -O input $bilibili_video_url
# 若下载后文件不是input.mp4，请参考一下命令(没试过):
# ./lux $bilibili_video_url -o - | ffmpeg -i - -c copy input.mp4

rm: cannot remove 'lux': No such file or directory
rm: cannot remove 'lux.tar.gz': No such file or directory
--2022-01-30 12:40:03--  https://github.com/iawia002/lux/releases/download/v0.12.0/lux_0.12.0_Linux_64-bit.tar.gz
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/122734569/335bb860-0434-46bb-885d-b05b3e66e8b8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220130%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220130T124003Z&X-Amz-Expires=300&X-Amz-Signature=704afd66cd6088e2439ce904ff3d977167308560e4c89decb0e9d94111bd9b9e&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=122734569&response-content-disposition=attachment%3B%20filename%3Dlux_0.12.0_Linux_64-bit.tar.gz&response-content-type=application%2Foctet-stream [following]
--2022-01-30 12:4

## 处理视频

In [28]:
!rm -rf ./videos
!mkdir videos
!ffmpeg -y -loglevel info -i input.mp4 -ss $cut_video_start_time -t $cut_video_time_interval videos/video.mp4

ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lib

# 安装依赖

## 查看版本

In [29]:
print("torch 版本:")
!python -c 'import torch; print(torch.__version__)'
print()
print("cuda 版本:")
!nvcc --version

torch 版本:
1.10.0+cu111

cuda 版本:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0


## 安装 Detectron2

In [30]:
# 请根据版本手动修改这里的代码(到官网复制)
!python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.10/index.html

Looking in links: https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.10/index.html


# 克隆VideoPose3D库

In [31]:
!rm VideoPose3D -rf
!git clone https://github.com/facebookresearch/VideoPose3D
!mkdir ./VideoPose3D/checkpoint

Cloning into 'VideoPose3D'...
remote: Enumerating objects: 121, done.
remote: Total 121 (delta 0), reused 0 (delta 0), pack-reused 121
Receiving objects: 100% (121/121), 9.53 MiB | 16.02 MiB/s, done.
Resolving deltas: 100% (41/41), done.


# 下载事先训练好的Human3.6m Coco Model

In [32]:
os.chdir('VideoPose3D/checkpoint')
!wget https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_detectron_coco.bin
os.chdir('..')

--2022-01-30 12:40:53--  https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_detectron_coco.bin
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.22.75.142, 172.67.9.4, 104.22.74.142, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.22.75.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67892577 (65M) [application/octet-stream]
Saving to: ‘pretrained_h36m_detectron_coco.bin’

pretrained_h36m_det 100%[===================>]  64.75M  68.0MB/s    in 1.0s    

2022-01-30 12:40:54 (68.0 MB/s) - ‘pretrained_h36m_detectron_coco.bin’ saved [67892577/67892577]



# 用Detectron2计算2D坐标

In [33]:
# !mkdir ../output
# os.chdir('inference')
# !python infer_video_d2.py \
#     --cfg COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x.yaml \
#     --output-dir ../../ouput \
#     --image-ext mp4 \
#     ../../videos
# os.chdir('..')
!pwd
os.chdir('..')
!rm output -rf
!mkdir output
!python /content/VideoPose3D/inference/infer_video_d2.py \
    --cfg COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x.yaml \
    --output-dir output \
    --image-ext mp4 \
    videos

/content/VideoPose3D/VideoPose3D
Processing videos/video.mp4
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --

# 创建自定义数据集

In [34]:
!mkdir ./VideoPose3D/data/detectron2output
!cp output/video.mp4.npz VideoPose3D/data/detectron2output/video.mp4.npz
os.chdir('VideoPose3D/data') # 必须要到这个目录下执行
!python prepare_data_2d_custom.py -i detectron2output -o myvideos
os.chdir('../../')

Parsing 2D detections from detectron2output
Processing detectron2output/video.mp4.npz
150 total frames processed
0 frames were interpolated
----------
Saving...
Done.


# 计算三维坐标

In [35]:
!cp ./videos/video.mp4 VideoPose3D/video.mp4
os.chdir('VideoPose3D')
!python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject video.mp4 --viz-action custom --viz-camera 0 --viz-video video.mp4 --viz-output output.mp4 --viz-export outputfile --viz-size 6

Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='myvideos', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export='outputfile', viz_limit=-1, viz_no_ground_truth=False, viz_output='output.mp4', viz_size=6, viz_skip=0, viz_subject='video.mp4', viz_video='video.mp4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Tr

# 查看数据

## 3D 关节坐标

In [36]:
import numpy as np
data  = np.load('outputfile.npy')
lst = data
# for item in lst: # 查看所有帧
#     print(item)
print(lst[0])  # 查看第一帧数据

[[-2.08045094e-07 -2.36595170e-05 -9.28365353e-07]
 [-1.14685714e-01  6.48771040e-03 -1.72227044e-02]
 [-7.72918910e-02  4.06089306e-01 -1.04552656e-01]
 [-5.28216735e-02  8.28379869e-01 -8.28702226e-02]
 [ 1.14685789e-01 -6.49400521e-03  1.72316115e-02]
 [ 1.02251604e-01  3.88020098e-01 -5.54155186e-02]
 [ 3.29971500e-02  7.88852155e-01  5.53925857e-02]
 [ 8.85959156e-03 -1.99542195e-01 -4.72787544e-02]
 [ 2.69613340e-02 -4.11004603e-01 -1.60159230e-01]
 [ 2.49196794e-02 -4.49327439e-01 -2.60384858e-01]
 [ 2.92549264e-02 -5.45706749e-01 -2.19850004e-01]
 [ 1.49023190e-01 -3.54216874e-01 -1.11483365e-01]
 [ 2.57860273e-01 -1.45624995e-01 -1.66703761e-02]
 [ 2.33126372e-01  3.06388494e-02 -1.69535682e-01]
 [-1.00413717e-01 -3.39481175e-01 -1.63041919e-01]
 [-2.02452242e-01 -1.03583455e-01 -2.13152438e-01]
 [-1.96540058e-02 -1.47502631e-01 -3.45219791e-01]]


## 视频

In [37]:
def show_local_mp4_video(file_name, width=640, height=480):
  import io
  import base64
  from IPython.display import HTML
  video_encoded = base64.b64encode(io.open(file_name, 'rb').read())
  return HTML(data='''<video width="{0}" height="{1}" alt="test" controls>
                        <source src="data:video/mp4;base64,{2}" type="video/mp4" />
                      </video>'''.format(width, height, video_encoded.decode('ascii')))

show_local_mp4_video('output.mp4', width=960, height=720)

# 下载数据

In [38]:
from google.colab import files

if download_joint_coordinates:
    files.download('outputfile.npy')

if download_video:
    files.download('output.mp4')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>